/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientesIndex.java
 *
 * Created on 25/09/2012, 15:43:11
 */
package views;

import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JTable;
import helpers.ButtonColumnDetalhar;

/**
 *
 * @author Schettino
 */
public class ClientesShow extends javax.swing.JFrame {
    
    public static final int COLUNA_ID = 0;
    public static final int COLUNA_NOME = 1;
    public static final int COLUNA_CPF = 2;
    public static final int COLUNA_RG = 3;
    public static final int COLUNA_PROCESSOS = 4;

    /** Creates new form ClientesIndex */
    public ClientesShow() {
        initComponents();
        
        ButtonColumnDetalhar buttonColumn = new ButtonColumnDetalhar(tableProcessos, COLUNA_PROCESSOS);
        //        tableClientes.setValueAt(buttonProcessos, 1, 3);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAtualizarDados = new javax.swing.JButton();
        labelDataNascimento = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        textCPF = new javax.swing.JLabel();
        labelRG = new javax.swing.JLabel();
        textDataNascimento = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        textRG = new javax.swing.JLabel();
        textTelefone = new javax.swing.JLabel();
        labelProcessos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProcessos = new javax.swing.JTable();
        buttonNovoProcesso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonAtualizarDados.setText("Atualizar Dados");
        buttonAtualizarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarDadosActionPerformed(evt);
            }
        });

        labelDataNascimento.setText("Data de Nascimento:");

        labelTelefone.setText("Telefone:");

        textCPF.setText("11111111111");

        labelRG.setText("RG:");

        textDataNascimento.setText("28/08/1989");

        labelCPF.setText("CPF:");

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 25));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Thiago Neves");

        textRG.setText("11111111-1");

        textTelefone.setText("87221228");

        labelProcessos.setFont(new java.awt.Font("Tahoma", 0, 15));
        labelProcessos.setText("Processos");

        tableProcessos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {new Integer(25), "Latrocínio", "25/09/2012", "Em julgamento", null},
                {new Integer(78), "Dopping", "28/08/2012", "Culpado", null}
            },
            new String [] {
                "#", "Artigo", "Data", "Situação", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProcessos);
        tableProcessos.getColumnModel().getColumn(0).setMinWidth(25);
        tableProcessos.getColumnModel().getColumn(0).setPreferredWidth(25);
        tableProcessos.getColumnModel().getColumn(0).setMaxWidth(40);

        buttonNovoProcesso.setText("Novo Processo");
        buttonNovoProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoProcessoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(labelTitulo)
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelProcessos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonAtualizarDados))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCPF)
                                    .addComponent(labelRG))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCPF)
                                    .addComponent(textRG))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDataNascimento)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTelefone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textTelefone)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDataNascimento)
                                .addGap(86, 86, 86))
                            .addComponent(buttonNovoProcesso)))
                    .addGap(25, 25, 25)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addContainerGap(333, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelCPF)
                                .addComponent(textCPF))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelRG)
                                .addComponent(textRG)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelTelefone)
                                .addComponent(textTelefone))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelDataNascimento)
                                .addComponent(textDataNascimento))))
                    .addGap(29, 29, 29)
                    .addComponent(buttonAtualizarDados)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(labelProcessos)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(buttonNovoProcesso)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAtualizarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarDadosActionPerformed

    }//GEN-LAST:event_buttonAtualizarDadosActionPerformed

    private void buttonNovoProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoProcessoActionPerformed

    }//GEN-LAST:event_buttonNovoProcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new ClientesShow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtualizarDados;
    private javax.swing.JButton buttonNovoProcesso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelProcessos;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tableProcessos;
    private javax.swing.JLabel textCPF;
    private javax.swing.JLabel textDataNascimento;
    private javax.swing.JLabel textRG;
    private javax.swing.JLabel textTelefone;
    // End of variables declaration//GEN-END:variables
}
